AWSTemplateFormatVersion: "2010-09-09"
Description: ffxiv-item-name-database-prepare

Parameters:
  HostName:
    Type: String
    Default: ffxiv-itndb.luciferous.xyz

Resources:
  APIHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref HostName

  Certificate:
    Type: AWS::CertificateManager::Certificate
    DependsOn: APIHostedZone
    Properties:
      DomainName: !Ref HostName
      ValidationMethod: DNS

Outputs:
  APIHostZoneNameServers:
    Value: !Join [",", !GetAtt APIHostedZone.NameServers]
