AWSTemplateFormatVersion: "2010-09-09"
Description: ffxiv-item-name-database-prepare

Parameters:
  HostName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/api-host-name

  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/hosted-zone-id

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref HostName
      DomainValidationOptions:
        - DomainName: !Ref HostName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
