AWSTemplateFormatVersion: "2010-09-09"
Description: ffxiv-item-name-database-prepare

Parameters:
  HostName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/api-host-name

  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/hosted-zone-id

  ApiDomainName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/api/api-domain-name

  ApiOriginPath:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/api/api-origin-path

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref HostName
      DomainValidationOptions:
        - DomainName: !Ref HostName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  CloudFrontLogBucket:
    Type: AWS::S3::Bucket

  DatabaseDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref HostName
        Origins:
          - Id: OriginApi
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            DomainName: !Ref ApiDomainName
            OriginPath: !Sub /${ApiOriginPath}
            CustomOriginConfig:
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - TLSv1
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        CacheBehaviors:
          - AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            TargetOriginId: OriginApi
            PathPattern: "*"
            DefaultTTL: 86400
            MaxTTL: 31536000
            MinTTL: 1
            ViewerProtocolPolicy: https-only
            ForwardedValues:
              QueryString: true
              QueryStringCacheKeys:
                - string
                - language
                - ids
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          TargetOriginId: OriginApi
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 1
          ViewerProtocolPolicy: https-only
          ForwardedValues:
            QueryString: true
            QueryStringCacheKeys:
              - string
              - language
              - ids
        IPV6Enabled: true
        Logging:
          Bucket: !GetAtt CloudFrontLogBucket.DomainName
          IncludeCookies: false

  CloudFrontRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      AliasTarget:
        DNSName: !GetAtt DatabaseDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        Type: A
        Name: !Ref HostName
