AWSTemplateFormatVersion: "2010-09-09"
Description: ffxiv-item-name-database-prepare

Parameters:
  HostName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/api-host-name

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref HostName
      ValidationMethod: DNS
